package sk.tuke.seregely.dipl.entity.model;

// Generated Mar 25, 2013 9:39:56 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CiselnikStavov generated by hbm2java
 */
public class CiselnikStavov implements java.io.Serializable {

	private int idStavu;
	private String nazovStavu;
	private Set stavJazdies = new HashSet(0);

	public CiselnikStavov() {
	}

	public CiselnikStavov(int idStavu) {
		this.idStavu = idStavu;
	}

	public CiselnikStavov(int idStavu, String nazovStavu, Set stavJazdies) {
		this.idStavu = idStavu;
		this.nazovStavu = nazovStavu;
		this.stavJazdies = stavJazdies;
	}

	public int getIdStavu() {
		return this.idStavu;
	}

	public void setIdStavu(int idStavu) {
		this.idStavu = idStavu;
	}

	public String getNazovStavu() {
		return this.nazovStavu;
	}

	public void setNazovStavu(String nazovStavu) {
		this.nazovStavu = nazovStavu;
	}

	public Set getStavJazdies() {
		return this.stavJazdies;
	}

	public void setStavJazdies(Set stavJazdies) {
		this.stavJazdies = stavJazdies;
	}

}
