package sk.tuke.seregely.dipl.entity.model;

import java.util.Date;

// Generated Mar 25, 2013 9:39:56 AM by Hibernate Tools 4.0.0

/**
 * StavJazdy generated by hbm2java
 */
public class StavJazdy implements java.io.Serializable {

	private int idStavuJazdy;
	private CiselnikStavov ciselnikStavov;
	private Uctovnik uctovnik;
	private Vodic vodic;
	private Veduci veduci;
	private Jazda jazda;
	private Date casZmeny;
	private String detailZmeny;

	public StavJazdy() {
	}

	public StavJazdy(int idStavuJazdy, CiselnikStavov ciselnikStavov) {
		this.idStavuJazdy = idStavuJazdy;
		this.ciselnikStavov = ciselnikStavov;
	}

	public StavJazdy(int idStavuJazdy, CiselnikStavov ciselnikStavov,
			Uctovnik uctovnik, Vodic vodic, Veduci veduci, Jazda jazda
			) {
		this.idStavuJazdy = idStavuJazdy;
		this.ciselnikStavov = ciselnikStavov;
		this.uctovnik = uctovnik;
		this.vodic = vodic;
		this.veduci = veduci;
		this.jazda = jazda;
	}

	public int getIdStavuJazdy() {
		return this.idStavuJazdy;
	}

	public void setIdStavuJazdy(int idStavuJazdy) {
		this.idStavuJazdy = idStavuJazdy;
	}

	public CiselnikStavov getCiselnikStavov() {
		return this.ciselnikStavov;
	}

	public void setCiselnikStavov(CiselnikStavov ciselnikStavov) {
		this.ciselnikStavov = ciselnikStavov;
	}

	public Uctovnik getUctovnik() {
		return this.uctovnik;
	}

	public void setUctovnik(Uctovnik uctovnik) {
		this.uctovnik = uctovnik;
	}

	public Vodic getVodic() {
		return this.vodic;
	}

	public void setVodic(Vodic vodic) {
		this.vodic = vodic;
	}

	public Veduci getVeduci() {
		return this.veduci;
	}

	public void setVeduci(Veduci veduci) {
		this.veduci = veduci;
	}

	public Jazda getJazda() {
		return this.jazda;
	}

	public void setJazda(Jazda jazda) {
		this.jazda = jazda;
	}
	
	public Date getCasZmeny() {
		return this.casZmeny;
	}

	public void setCasZmeny(Date casZmeny) {
		this.casZmeny = casZmeny;
	}
	
	public String getDetailZmeny() {
		return this.detailZmeny;
	}

	public void setDetailZmeny(String detail) {
		this.detailZmeny = detail;
	}
}
