package sk.tuke.seregely.dipl.entity.model;

// Generated Mar 18, 2013 10:50:03 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Tankovanie generated by hbm2java
 */
public class Tankovanie implements java.io.Serializable {

	private Date casTankovania;
	private int idVozidla;
	private Integer typPaliva;

	public Tankovanie() {
	}

	public Tankovanie(Date casTankovania, int idVozidla) {
		this.casTankovania = casTankovania;
		this.idVozidla = idVozidla;
	}

	public Tankovanie(Date casTankovania, int idVozidla, Integer typPaliva) {
		this.casTankovania = casTankovania;
		this.idVozidla = idVozidla;
		this.typPaliva = typPaliva;
	}

	public Date getCasTankovania() {
		return this.casTankovania;
	}

	public void setCasTankovania(Date casTankovania) {
		this.casTankovania = casTankovania;
	}

	public int getIdVozidla() {
		return this.idVozidla;
	}

	public void setIdVozidla(int idVozidla) {
		this.idVozidla = idVozidla;
	}

	public Integer getTypPaliva() {
		return this.typPaliva;
	}

	public void setTypPaliva(Integer typPaliva) {
		this.typPaliva = typPaliva;
	}

}
