package sk.tuke.seregely.dipl.entity.model;

import java.util.HashSet;
import java.util.Set;

// Generated Mar 18, 2013 10:50:03 AM by Hibernate Tools 4.0.0

/**
 * Veduci generated by hbm2java
 */
public class Veduci implements java.io.Serializable {

	private int idVeduceho;
	private Pracovisko pracovisko;
	private String celeMeno;
	private String email;
	private Set stavJazdies = new HashSet(0);

	public Veduci() {
	}

	public Veduci(int idVeduceho) {
		this.idVeduceho = idVeduceho;
	}

	public Veduci(int idVeduceho, Pracovisko pracovisko, String celeMeno) {
		this.idVeduceho = idVeduceho;
		this.pracovisko = pracovisko;
		this.celeMeno = celeMeno;
	}

	public int getIdVeduceho() {
		return this.idVeduceho;
	}

	public void setIdVeduceho(int idVeduceho) {
		this.idVeduceho = idVeduceho;
	}

	public Pracovisko getPracovisko() {
		return this.pracovisko;
	}

	public void setPracovisko(Pracovisko pracovisko) {
		this.pracovisko = pracovisko;
	}

	public String getCeleMeno() {
		return this.celeMeno;
	}

	public void setCeleMeno(String celeMeno) {
		this.celeMeno = celeMeno;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public Set getStavJazdies() {
		return this.stavJazdies;
	}

	public void setStavJazdies(Set stavJazdies) {
		this.stavJazdies = stavJazdies;
	}

}
