package sk.tuke.seregely.dipl.entity.model;

// Generated Mar 18, 2013 10:50:03 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Vozidlo generated by hbm2java
 */
public class Vozidlo implements java.io.Serializable {

	private int idVozidla;
	private String spz;
	private Float skutocnyStavPaliva;
	private Float tachometer;
	private String typVozidla;
	private Set vozidloVodics = new HashSet(0);

	public Vozidlo() {
	}

	public Vozidlo(int idVozidla) {
		this.idVozidla = idVozidla;
	}

	public Vozidlo(int idVozidla, String spz, Float skutocnyStavPaliva,
			String typVozidla, Set vozidloVodics) {
		this.idVozidla = idVozidla;
		this.spz = spz;
		this.skutocnyStavPaliva = skutocnyStavPaliva;
		this.typVozidla = typVozidla;
		this.vozidloVodics = vozidloVodics;
	}

	public int getIdVozidla() {
		return this.idVozidla;
	}

	public void setIdVozidla(int idVozidla) {
		this.idVozidla = idVozidla;
	}

	public String getSpz() {
		return this.spz;
	}

	public void setSpz(String spz) {
		this.spz = spz;
	}

	public Float getSkutocnyStavPaliva() {
		return this.skutocnyStavPaliva;
	}

	public void setSkutocnyStavPaliva(Float skutocnyStavPaliva) {
		this.skutocnyStavPaliva = skutocnyStavPaliva;
	}
	
	public Float getTachometer() {
		return this.tachometer;
	}

	public void setTachometer(Float tach) {
		this.tachometer = tach;
	}

	public String getTypVozidla() {
		return this.typVozidla;
	}

	public void setTypVozidla(String typVozidla) {
		this.typVozidla = typVozidla;
	}

	public Set getVozidloVodics() {
		return this.vozidloVodics;
	}

	public void setVozidloVodics(Set vozidloVodics) {
		this.vozidloVodics = vozidloVodics;
	}

}
