package sk.tuke.seregely.dipl.entity.model;

// Generated Mar 18, 2013 10:50:03 AM by Hibernate Tools 4.0.0

/**
 * Zakazka generated by hbm2java
 */
public class Zakazka implements java.io.Serializable {

	private int idZakazky;
	private String nazov;
	private String kod;
	private String popis;

	public Zakazka() {
	}

	public Zakazka(int idZakazky) {
		this.idZakazky = idZakazky;
	}

	public Zakazka(int idZakazky, String nazov, String kod, String popis) {
		this.idZakazky = idZakazky;
		this.nazov = nazov;
		this.kod = kod;
		this.popis = popis;
	}

	public int getIdZakazky() {
		return this.idZakazky;
	}

	public void setIdZakazky(int idZakazky) {
		this.idZakazky = idZakazky;
	}

	public String getNazov() {
		return this.nazov;
	}

	public void setNazov(String nazov) {
		this.nazov = nazov;
	}

	public String getKod() {
		return this.kod;
	}

	public void setKod(String kod) {
		this.kod = kod;
	}

	public String getPopis() {
		return this.popis;
	}

	public void setPopis(String popis) {
		this.popis = popis;
	}

}
